import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';
import { Attendance, Staff, Branch } from '../types';

export interface AttendancePdfParams {
  title?: string;
  periodType: 'month' | 'year' | 'custom';
  month?: number;
  year: number;
  startDate?: string;
  endDate?: string;
  staff?: Staff | null;
  branch?: Branch | null;
  records: Attendance[];
  generatedBy?: string;
}

export async function generateAttendancePdf(params: AttendancePdfParams) {
  const {
    periodType,
    month = new Date().getMonth() + 1,
    year,
    startDate,
    endDate,
    staff,
    branch,
    records,
    generatedBy = 'Admin'
  } = params;

  const pdf = new jsPDF({
    orientation: 'portrait',
    unit: 'mm',
    format: 'a4'
  });

  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();

  // 1. Month / Period Text
  const monthNames = [
    'January', 'February', 'March', 'April', 'May', 'June',
    'July', 'August', 'September', 'October', 'November', 'December'
  ];
  let periodText = '';
  if (periodType === 'month') {
    periodText = `${monthNames[month - 1]} ${year}`;
  } else if (periodType === 'year') {
    periodText = `Year ${year}`;
  } else {
    periodText = `${startDate || ''} to ${endDate || ''}`;
  }

  // 2. Metrics Calculation
  const totalDays = records.length;
  let totalHours = 0;
  let totalOtHours = 0;
  let presentCount = 0;
  let lateCount = 0;
  let absentCount = 0;
  let completedCount = 0;

  records.forEach(r => {
    totalHours += r.workHours || 0;
    totalOtHours += r.overtimeHours || 0;
    if (r.status === 'Present' || r.status === 'Working') presentCount++;
    if (r.status === 'Completed') completedCount++;
    if (r.status === 'Late') lateCount++;
    if (r.status === 'Absent') absentCount++;
  });

  // 3. Header Top Bar
  pdf.setFillColor(0, 61, 155); // #003D9B
  pdf.rect(0, 0, pageWidth, 24, 'F');

  pdf.setTextColor(255, 255, 255);
  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(16);
  pdf.text('CLEAN24 LAUNDRY SYSTEM', 14, 11);

  pdf.setFontSize(9);
  pdf.setFont('helvetica', 'normal');
  pdf.text('STAFF ATTENDANCE & WORKING HOURS REPORT', 14, 18);

  pdf.setFontSize(8);
  pdf.text(`Period: ${periodText}`, pageWidth - 14, 11, { align: 'right' });
  pdf.text(`Generated: ${new Date().toLocaleDateString('en-GB')}`, pageWidth - 14, 18, { align: 'right' });

  // 4. Staff / Scope Summary Info Box
  pdf.setFillColor(248, 250, 252);
  pdf.setDrawColor(226, 232, 240);
  pdf.roundedRect(14, 28, pageWidth - 28, 24, 2, 2, 'FD');

  pdf.setTextColor(30, 41, 59);
  pdf.setFontSize(9);
  pdf.setFont('helvetica', 'bold');
  pdf.text('REPORT DETAILS', 18, 34);

  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(8.5);
  pdf.setTextColor(71, 85, 105);

  const staffNameStr = staff ? `${staff.fullName} (${staff.position || 'Staff'})` : 'All Active Staff Members';
  const branchNameStr = branch ? branch.branchName : 'All Branches (Overall)';

  pdf.text(`Staff Name:`, 18, 41);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(15, 23, 42);
  pdf.text(staffNameStr, 40, 41);

  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(71, 85, 105);
  pdf.text(`Branch:`, 18, 47);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(15, 23, 42);
  pdf.text(branchNameStr, 40, 47);

  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(71, 85, 105);
  pdf.text(`Staff ID:`, pageWidth / 2 + 10, 41);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(15, 23, 42);
  pdf.text(staff?.idCardNumber || staff?.phone || 'N/A', pageWidth / 2 + 28, 41);

  pdf.setFont('helvetica', 'normal');
  pdf.setTextColor(71, 85, 105);
  pdf.text(`Generated By:`, pageWidth / 2 + 10, 47);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(15, 23, 42);
  pdf.text(generatedBy, pageWidth / 2 + 35, 47);

  // 5. Four Key Summary Stat Badges
  const boxY = 56;
  const boxWidth = (pageWidth - 28 - 9) / 4;
  const boxHeight = 16;

  // Box 1: Total Days
  pdf.setFillColor(239, 246, 255);
  pdf.setDrawColor(191, 219, 254);
  pdf.roundedRect(14, boxY, boxWidth, boxHeight, 2, 2, 'FD');
  pdf.setFontSize(7.5);
  pdf.setTextColor(30, 64, 175);
  pdf.setFont('helvetica', 'normal');
  pdf.text('TOTAL DAYS', 14 + boxWidth / 2, boxY + 5.5, { align: 'center' });
  pdf.setFontSize(11);
  pdf.setFont('helvetica', 'bold');
  pdf.text(String(totalDays), 14 + boxWidth / 2, boxY + 12, { align: 'center' });

  // Box 2: Total Work Hours
  pdf.setFillColor(240, 253, 244);
  pdf.setDrawColor(187, 247, 208);
  pdf.roundedRect(14 + boxWidth + 3, boxY, boxWidth, boxHeight, 2, 2, 'FD');
  pdf.setFontSize(7.5);
  pdf.setTextColor(22, 101, 52);
  pdf.setFont('helvetica', 'normal');
  pdf.text('TOTAL WORK HOURS', 14 + boxWidth + 3 + boxWidth / 2, boxY + 5.5, { align: 'center' });
  pdf.setFontSize(11);
  pdf.setFont('helvetica', 'bold');
  pdf.text(`${totalHours.toFixed(1)} hrs`, 14 + boxWidth + 3 + boxWidth / 2, boxY + 12, { align: 'center' });

  // Box 3: Overtime
  pdf.setFillColor(254, 243, 199);
  pdf.setDrawColor(253, 230, 138);
  pdf.roundedRect(14 + (boxWidth + 3) * 2, boxY, boxWidth, boxHeight, 2, 2, 'FD');
  pdf.setFontSize(7.5);
  pdf.setTextColor(146, 64, 14);
  pdf.setFont('helvetica', 'normal');
  pdf.text('OVERTIME (OT)', 14 + (boxWidth + 3) * 2 + boxWidth / 2, boxY + 5.5, { align: 'center' });
  pdf.setFontSize(11);
  pdf.setFont('helvetica', 'bold');
  pdf.text(`${totalOtHours.toFixed(1)} hrs`, 14 + (boxWidth + 3) * 2 + boxWidth / 2, boxY + 12, { align: 'center' });

  // Box 4: Completed & Present
  pdf.setFillColor(245, 243, 255);
  pdf.setDrawColor(221, 214, 254);
  pdf.roundedRect(14 + (boxWidth + 3) * 3, boxY, boxWidth, boxHeight, 2, 2, 'FD');
  pdf.setFontSize(7.5);
  pdf.setTextColor(91, 33, 182);
  pdf.setFont('helvetica', 'normal');
  pdf.text('ON-TIME / ATTENDED', 14 + (boxWidth + 3) * 3 + boxWidth / 2, boxY + 5.5, { align: 'center' });
  pdf.setFontSize(11);
  pdf.setFont('helvetica', 'bold');
  pdf.text(`${completedCount + presentCount} days`, 14 + (boxWidth + 3) * 3 + boxWidth / 2, boxY + 12, { align: 'center' });

  // 6. Attendance Records Table
  const formatPdfDuration = (hours?: number): string => {
    if (hours === undefined || hours === null || isNaN(hours) || hours === 0) return '0h';
    const totalMins = Math.round(hours * 60);
    const h = Math.floor(totalMins / 60);
    const m = totalMins % 60;
    if (h === 0) return `${m}m`;
    if (m === 0) return `${h}h`;
    return `${h}h ${m}m`;
  };

  const tableRows = records.map((r, index) => {
    const d = new Date(r.date);
    const dayNames = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
    const dayOfWeek = isNaN(d.getTime()) ? '' : dayNames[d.getDay()];

    return [
      String(index + 1),
      `${r.date} (${dayOfWeek})`,
      staff ? (r.shiftType || 'Full-Time') : (r.staffName || 'Staff'),
      r.checkIn || '--',
      r.checkOut || '--',
      formatPdfDuration(r.workHours),
      r.overtimeHours ? `${r.overtimeHours}h` : '0h',
      r.status || 'Present',
      r.source === 'telegram' ? 'Telegram' : 'Web Manual'
    ];
  });

  autoTable(pdf, {
    startY: 77,
    margin: { left: 14, right: 14 },
    head: [[
      '#',
      'Date',
      staff ? 'Shift' : 'Employee Name',
      'Check In',
      'Check Out',
      'Work Hrs',
      'OT Hrs',
      'Status',
      'Source'
    ]],
    body: tableRows,
    theme: 'striped',
    headStyles: {
      fillColor: [0, 61, 155],
      textColor: [255, 255, 255],
      fontSize: 8,
      fontStyle: 'bold',
      halign: 'center',
      valign: 'middle',
      cellPadding: 2.5
    },
    styles: {
      fontSize: 7.5,
      cellPadding: 2,
      valign: 'middle',
      textColor: [30, 41, 59]
    },
    columnStyles: {
      0: { halign: 'center', cellWidth: 8 },
      1: { halign: 'left', cellWidth: 26 },
      2: { halign: 'left', cellWidth: staff ? 22 : 36 },
      3: { halign: 'center', cellWidth: 20 },
      4: { halign: 'center', cellWidth: 20 },
      5: { halign: 'center', cellWidth: 16 },
      6: { halign: 'center', cellWidth: 14 },
      7: { halign: 'center', cellWidth: 20 },
      8: { halign: 'center', cellWidth: 22 }
    },
    alternateRowStyles: {
      fillColor: [248, 250, 252]
    },
    didDrawPage: (data) => {
      // Footer on every page
      const pageNum = pdf.internal.pages.length - 1;
      pdf.setFontSize(7);
      pdf.setTextColor(148, 163, 184);
      pdf.text(
        `Clean24 Laundry Management System • Confidential Staff Attendance Report`,
        14,
        pageHeight - 8
      );
      pdf.text(
        `Page ${data.pageNumber}`,
        pageWidth - 14,
        pageHeight - 8,
        { align: 'right' }
      );
    }
  });

  // 7. Signature Block at the end
  let finalY = (pdf as any).lastAutoTable.finalY + 12;
  if (finalY > pageHeight - 35) {
    pdf.addPage();
    finalY = 25;
  }

  pdf.setFontSize(8.5);
  pdf.setFont('helvetica', 'bold');
  pdf.setTextColor(30, 41, 59);

  pdf.text('PREPARED BY', 30, finalY);
  pdf.line(20, finalY + 16, 65, finalY + 16);
  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(7.5);
  pdf.setTextColor(100, 116, 139);
  pdf.text('HR / Store Supervisor', 25, finalY + 20);

  pdf.setFont('helvetica', 'bold');
  pdf.setFontSize(8.5);
  pdf.setTextColor(30, 41, 59);
  pdf.text('APPROVED BY', pageWidth - 55, finalY);
  pdf.line(pageWidth - 65, finalY + 16, pageWidth - 20, finalY + 16);
  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(7.5);
  pdf.setTextColor(100, 116, 139);
  pdf.text('Branch Manager / Owner', pageWidth - 60, finalY + 20);

  // 8. Output Filename
  const safeStaffName = staff ? staff.fullName.replace(/\s+/g, '_') : 'All_Staff';
  const safePeriod = periodType === 'month' ? `${monthString(month)}_${year}` : String(year);
  const fileName = `Clean24_Attendance_${safeStaffName}_${safePeriod}.pdf`;

  pdf.save(fileName);
}

function monthString(m: number): string {
  return String(m).padStart(2, '0');
}